# Site settings
title: Immutable
header-img: img/home-bg.png
email: emily.jirles@gmail.com
copyright_name: Jirles
description: > # this means to ignore newlines until "baseurl:"
  some things should never change
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Jirles
learn_profile: Jirles
email_username: emily.jirles@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
